services:
  app-data:
    build: ./appdata/
    container_name: app-data-container
    volumes:
     - ./www/html/:/var/www/html/
    command: "true"

  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
     - 80:80
    depends_on:
     - "php"
    volumes_from:
     - app-data

  php:
    build: ./php/
    container_name: php-container
    expose:
     - 9000
    volumes_from:
     - app-data

  mysql:
    image: mysql:latest
    container_name: mysql-container
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass


   
